#!/usr/bin/perl
#
# Copyright 2020 Adithyan K V
#
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script is a modified version of the default battery function that comes with
# i3blocks. It gives a visual representation of battery left, while removing the
# "CH/DIS" text labels in the original script
#
# USED fontawesome glyphs. Needs font awesome to work.
#
# This script is meant to use with i3blocks. It parses the output of the "acpi"
# command (often provided by a package of the same name) to read the status of
# the battery, and eventually its remaining time (to full charge or discharge).
#
# The icon will gradually change for a percentage below 85%, and the urgency
# (exit code 33) is set if there is less that 5% remaining.

use strict;
use warnings;
use utf8;

my $acpi;
my $status;
my $percent;
my $full_text;
my $short_text;
my $bat_number = $ENV{BLOCK_INSTANCE} || 0;

# read the first line of the "acpi" command output
open (ACPI, "acpi -b | grep 'Battery $bat_number' |") or die;
$acpi = <ACPI>;
close(ACPI);

# fail on unexpected output
if ($acpi !~ /: (\w+), (\d+)%/) {
	die "$acpi\n";
}

$status = $1;
$percent = $2;
$full_text = "";

if ($status eq 'Discharging') {
	if ($percent < 10) {
		#show battery empty
		$full_text .= ''
	} elsif ($percent < 30) {
		#show battery quarter full
		$full_text .= ''
	} elsif ($percent < 60) {
		#show battery half full
		$full_text .= ''
	} elsif ($percent < 80) {
		#show battery three quarters full
		$full_text .= ''
	} elsif ($percent < 101) {
		#full battery icon font awesome
		$full_text .= ''
	}

	if ($percent < 5) {
		exit(33);
	}
} elsif ($status eq 'Charging') {
	#show plug symbol if charging
	$full_text .= '';
}

$full_text .= " $percent%";

$short_text = $full_text;

# if ($acpi =~ /(\d\d:\d\d):/) {
# 	$full_text .= " ($1)";
# }

# print text
print "$full_text\n";
print "$short_text\n";

# consider color and urgent flag only on discharge
if ($status eq 'Discharging') {

	if ($percent < 20) {
		print "#FF0000\n";
	} elsif ($percent < 40) {
		print "#F29C6B\n";
	} 

	if ($percent < 5) {
		exit(33);
	}
}

exit(0);
